#!/bin/bash
set -euo pipefail

HIFI_BAM=$1
GENOME=$2
PREFIX=Ksch
THREADS=32

mkdir -p HiMT organelle_screening


# 1. Convert PacBio HiFi BAM to FASTA
samtools fasta -@ ${THREADS} \
    ${HIFI_BAM} \
    > HiMT/${PREFIX}.HiFi.fa


# 2. Assemble chloroplast and mitochondrial genomes using HiMT
himt assemble \
    -i HiMT/${PREFIX}.HiFi.fa \
    -o HiMT/${PREFIX}_organelle \
    -t ${THREADS}


# 3. Specify chloroplast and mitochondrial assemblies generated by HiMT
# Replace these two paths with the actual HiMT output FASTA files
CP=HiMT/${PREFIX}_organelle/chloroplast.fa
MT=HiMT/${PREFIX}_organelle/mitochondrial.fa


# 4. Align nuclear genome assembly against organellar genomes
minimap2 -x asm5 -t ${THREADS} \
    ${GENOME} ${CP} \
    > organelle_screening/${PREFIX}.cp.paf

minimap2 -x asm5 -t ${THREADS} \
    ${GENOME} ${MT} \
    > organelle_screening/${PREFIX}.mt.paf


# 5. Merge organellar alignment regions
for TYPE in cp mt
do
    awk 'BEGIN{OFS="\t"} {print $1,$3,$4}' \
        organelle_screening/${PREFIX}.${TYPE}.paf | \
        sort -k1,1 -k2,2n | \
        bedtools merge -i - \
        > organelle_screening/${PREFIX}.${TYPE}.merged.bed
done


# 6. Identify scaffolds with >=50% organellar coverage
samtools faidx ${GENOME}

for TYPE in cp mt
do
    awk '
    NR==FNR {len[$1]=$2; next}
    {cov[$1]+=$3-$2}
    END {
        for (id in len)
            if (cov[id]/len[id] >= 0.5)
                print id
    }' \
    ${GENOME}.fai \
    organelle_screening/${PREFIX}.${TYPE}.merged.bed \
    > organelle_screening/${PREFIX}.${TYPE}.candidate.ids
done


# 7. Remove candidate organelle-derived scaffolds
cat organelle_screening/${PREFIX}.cp.candidate.ids \
    organelle_screening/${PREFIX}.mt.candidate.ids | \
    sort -u \
    > organelle_screening/${PREFIX}.organelle_candidate.ids

seqkit grep -v \
    -f organelle_screening/${PREFIX}.organelle_candidate.ids \
    ${GENOME} \
    > organelle_screening/${PREFIX}.no_organelle.fa
